services:
  vproapp:
    build:
      context: ./Docker-files/app
      dockerfile: Dockerfile
    image: adamczepiel/vproapp:latest
    container_name: vproapp
    ports: 
    - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps
  vproweb:
    container_name: vproweb 
    build:
      context: ./Docker-files/web
      dockerfile: Dockerfile
    image: adamczepiel/vproweb:latest
    ports: 
    - "80:80"
  vprodb: 
    build:
      context: ./Docker-files/db
      dockerfile: Dockerfile
    image: adamczepiel/mysql:latest
    container_name: vprodb
    ports: 
    - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass
    volumes: 
      - vprodbdata:/var/lib/mysql
  vprocache01:
    image: memcached
    container_name: vprocache01
    ports: 
    - "11211:11211"
  vpromq01:
    image: rabbitmq
    container_name: vpromq01
    ports:
    - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest 
      - RABBITMQ_DEFAULT_PASS=guest 

volumes:
  vprodbdata: {}
  vproappdata: {}